version: 2
jobs:
  test:
    docker:
      - image: circleci/python:2.7-jessie

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r setup/requirements.txt
            pip install flake8

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup/requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cp sal/example_settings.py sal/settings.py
            python manage.py test
            python manage.py migrate
      - run:
          name: run linting
          command: |
            . venv/bin/activate
            flake8

      - store_artifacts:
          path: test-reports
          destination: test-reports
  build_latest:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t grahamgilbert/sal-manual:latest .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push grahamgilbert/sal-manual:latest

  build_branch:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t grahamgilbert/sal-manual:$CIRCLE_BRANCH .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push grahamgilbert/sal-manual:$CIRCLE_BRANCH

  build_tag:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t grahamgilbert/sal-manual:$CIRCLE_TAG .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push grahamgilbert/sal-manual:$CIRCLE_TAG

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build_latest:
          requires:
            - test
          filters:
            branches:
              only: master
      - build_branch:
          requires:
            - test
          filters:
            branches:
              ignore: master
      - build_tag:
          requires:
            - test
          filters:
            tags:
              only: /^\S.*/